description = "Conteúdo sobre desenvolvimento de software"
homepage = "http://neni.dev"
tags = ["Blog", "Responsive", "Personal", "Minimal", "Clean", "Disqus", "Google Analytics"]

# ctrlp ignora dist
# alguns projetos do php public pode ser uma pasta importante
publishDir = "dist"

baseURL = "http://wtf.neni.dev/"
languageCode = "pt-br"
title = "wtf Neni?"

[params]
  author = "Neni"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/"

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
